
# ========= Border =========
file_panel_border = '#333534'
sidebar_border = '#333534'
footer_border = '#333534'

# ========= Border Active =========
file_panel_border_active = '#59635e'
sidebar_border_active = '#59635e'
footer_border_active = '#59635e'
modal_border_active = '#59635e'

# ========= Background (bg) =========
full_screen_bg = '#EAEAEA'
file_panel_bg = '#EAEAEA'
sidebar_bg = '#EAEAEA'
footer_bg = '#EAEAEA'
modal_bg = '#EAEAEA'

# ========= Foreground (fg) =========
full_screen_fg = '#262827'
file_panel_fg = '#262827'
sidebar_fg = '#262827'
footer_fg = '#262827'
modal_fg = '#262827'

# ========= Special Color =========
cursor = '#262827'
correct = '#58615d'
error = '#4a514d'
hint = '#505854'
cancel = '#4a514d'
gradient_color = ['#EAEAEA', "#3f4241"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = '#EAEAEA'
file_panel_top_path = '#3f4241'
file_panel_item_selected_fg = '#3f4241'
file_panel_item_selected_bg = '#EAEAEA'

# ========= Sidebar Special Items =========
sidebar_title = '#262827'
sidebar_item_selected_fg = '#3f4241'
sidebar_item_selected_bg = '#EAEAEA'
sidebar_divider = '#333534'

# ========= Modal Special Items =========
modal_cancel_fg = "#383838"
modal_cancel_bg = '#4a514d'
modal_confirm_fg = "#383838"
modal_confirm_bg = '#58615d'
