[colors]
[colors.primary]
background = "#32302f"
foreground = "#f0e4c5"

[colors.normal]
black   = "#32302f"
red     = "#cc241d"
green   = "#a89984"
yellow  = "#ebdbb2"
blue    = "#706e6b"
magenta = "#afa499"
cyan    = "#d4bd99"
white   = "#fbf1c7"

[colors.bright]
black   = "#7b6d60"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#f0e4c5"

[colors.cursor]
text   = "#32302f"
cursor = "#f0e4c5"
