[colors.primary]
background = "#2c2525"
foreground = "#e6d9db"

[colors.cursor]
text = "#2c2525"
cursor = "#c3b7b8"

[colors.vi_mode_cursor]
text = "#2c2525"
cursor = "#c3b7b8"

[colors.search.matches]
foreground = "#2c2525"
background = "#f9cc6c"

[colors.search.focused_match]
foreground = "#2c2525"
background = "#fd6883"

[colors.footer_bar]
foreground = "#2c2525"
background = "#e6d9db"

[colors.selection]
text = "#e6d9db"
background = "#403e41"

[colors.normal]
black = "#72696a"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#f38d70"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#e6d9db"

[colors.bright]
black = "#948a8b"
red = "#ff8297"
green = "#c8e292"
yellow = "#fcd675"
blue = "#f8a788"
magenta = "#bebffd"
cyan = "#9bf1e1"
white = "#f1e5e7"
