[colors]
[colors.primary]
background = "#e3dfd4"
foreground = "#000000"

[colors.normal]
# This color is now distinct from the background for visibility
black   = "#8a8375"
# Slight adjustment for better distinction
red     = "#9e6f47"
green   = "#6e783a"
yellow  = "#877d40"
# Slight adjustment for better distinction
blue    = "#6e703d"
magenta = "#79683a"
# Slight adjustment for better distinction
cyan    = "#656536"
white   = "#212121"

[colors.bright]
black   = "#757575"
red     = "#c2ab75"
green   = "#636d2c"
yellow  = "#bcb066"
blue    = "#b9a160"
magenta = "#b69d59"
cyan    = "#b39e51"
white   = "#000000"

[colors.cursor]
text   = "#e3dfd4"
cursor = "#000000"
